version: '3.8'
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=db_vex
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql